# Copyright (C) 2023 psionicprjkt

name: build-ksu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Git Config
        run: |
          git config --global user.name "KitsuNeko" && git config --global user.email konjikin5@gmail.com

      - name: Download Resources
        run: |
          git clone --depth=1 https://github.com/vlihjml/kernel mt6785 && cd mt6785
          wget --quiet https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-12.0.0_r12/clang-r416183b1.tar.gz -O "aosp-clang.tar.gz"
          mkdir clang && tar -xf aosp-clang.tar.gz -C clang && rm -rf aosp-clang.tar.gz
          
      - name: Update Latest KernelSU
        run: |
          cd mt6785 && rm -rf KernelSU && curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

      - name: Build Kernel
        run: |
          cd mt6785 && . build-ksu.sh

      - name: Set Release Date
        run: |
          echo "RELEASE_DATE=$(date +"%d%m%Y")" >> "$GITHUB_ENV"

      - name: Release Kernel
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "KernelSU"
          prerelease: false
          title: surya-${{ env.RELEASE_DATE }}-KernelSU
          files: |
             mt6785/AnyKernel/surya*
