# Copyright (C) 2023 psionicprjkt

name: build-ksu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Git Config
        run: |
          git config --global user.name "KitsuNeko" && git config --global user.email konjikin5@gmail.com

      - name: Download Resources
        run: |
          git clone --depth=1 https://github.com/vlihjml/kernel mt6785 && cd mt6785
          git clone --depth=1 https://github.com/psionicprjkt/aarch64-linux-android-4.9 arm64 && git clone --depth=1 https://github.com/psionicprjkt/arm-linux-androideabi-4.9 arm32
          git clone --depth=1 https://gitlab.com/LeCmnGend/clang.git -b clang-13 clang
          
      - name: Update Latest KernelSU
        run: |
          cd mt6785 && rm -rf KernelSU && curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

      - name: Build Kernel
        run: |
          cd mt6785 && . build-ksu.sh

      - name: Set Release Date
        run: |
          echo "RELEASE_DATE=$(date +"%d%m%Y")" >> "$GITHUB_ENV"

      - name: Release Kernel
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "KernelSU"
          prerelease: false
          title: surya-${{ env.RELEASE_DATE }}-KernelSU
          files: |
             mt6785/AnyKernel/surya*
