# Copyright (C) 2023 psionicprjkt

name: build-normal

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Git Config
        run: |
          git config --global user.name "officialputuid" && git config --global user.email officialputuid@hack.id

      - name: Download Resources
        run: |
          git clone --recursive https://github.com/vlihjml/kernel mt6785 && cd mt6785
          git clone --depth=1 https://github.com/psionicprjkt/aarch64-linux-android-4.9 arm64 && git clone --depth=1 https://github.com/psionicprjkt/arm-linux-androideabi-4.9 arm32
           wget --quiet https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-12.0.0_r12/clang-r416183b1.tar.gz -O "aosp-clang.tar.gz"
           mkdir clang && tar -xf aosp-clang.tar.gz -C clang && rm -rf aosp-clang.tar.gz
           
      - name: Trigger KSU Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run ksu.yml --ref R-based

      - name: Disable KernelSU Hooks
        run: |
          cd mt6785
          sed -i 's/CONFIG_KSU=y/CONFIG_KSU=n/' arch/arm64/configs/surya_defconfig

      - name: Build Kernel
        run: |
          cd mt6785 && . build-normal.sh

      - name: Set Release Date
        run: |
          echo "RELEASE_DATE=$(date +"%d%m%Y")" >> "$GITHUB_ENV"

      - name: Release Kernel
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "Normal"
          prerelease: false
          title: psionic-kernel-RM6785-${{ env.RELEASE_DATE }}-Normal
          files: |
            mt6785/AnyKernel/surya*
